/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoinBundle {
  'id' : bigint,
  'coins' : bigint,
  'product' : Product,
}
export interface ManualOrder {
  'id' : bigint,
  'verified' : boolean,
  'paymentMethod' : string,
  'username' : string,
  'blocked' : boolean,
  'email' : string,
  'totalINR' : bigint,
  'timestamp' : Time,
  'items' : Array<ManualOrderItem>,
  'screenshotBase64' : string,
}
export interface ManualOrderItem {
  'name' : string,
  'quantity' : bigint,
  'priceINR' : bigint,
}
export interface ManualOrderLite {
  'id' : bigint,
  'verified' : boolean,
  'paymentMethod' : string,
  'username' : string,
  'blocked' : boolean,
  'email' : string,
  'totalINR' : bigint,
  'timestamp' : Time,
  'items' : Array<ManualOrderItem>,
  'hasScreenshot' : boolean,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'priceCents' : bigint,
}
export type ProductType = { 'coinBundle' : CoinBundle } |
  { 'rank' : Rank };
export interface Purchase {
  'id' : bigint,
  'paymentSessionId' : string,
  'purchaseTime' : Time,
  'productId' : bigint,
  'productType' : ProductType,
  'caller' : Principal,
  'priceCents' : bigint,
}
export interface Rank { 'id' : bigint, 'tier' : string, 'product' : Product }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreInfo {
  'coinBundles' : Array<CoinBundle>,
  'coinBundleMultiplier' : bigint,
  'currency' : string,
  'rankDescription' : string,
  'ranks' : Array<Rank>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'id' : Principal, 'username' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCoinBundle' : ActorMethod<[bigint, bigint], undefined>,
  'addRank' : ActorMethod<[string, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockManualOrder' : ActorMethod<[bigint], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteManualOrder' : ActorMethod<[bigint], boolean>,
  'getCallerPurchases' : ActorMethod<[], Array<Purchase>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getManualOrders' : ActorMethod<[], Array<ManualOrder>>,
  'getManualOrdersLite' : ActorMethod<[], Array<ManualOrderLite>>,
  'getOrderScreenshot' : ActorMethod<[bigint], string>,
  'getPurchases' : ActorMethod<[], Array<Purchase>>,
  'getStore' : ActorMethod<[], StoreInfo>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedPurchaseIds' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markManualOrderVerified' : ActorMethod<[bigint], boolean>,
  'markPurchaseVerified' : ActorMethod<[bigint], boolean>,
  'purchaseProduct' : ActorMethod<
    [bigint, ProductType, bigint, string],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitManualOrder' : ActorMethod<
    [string, string, Array<ManualOrderItem>, bigint, string, string],
    bigint
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];