/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'priceCents' : IDL.Nat,
});
export const CoinBundle = IDL.Record({
  'id' : IDL.Nat,
  'coins' : IDL.Nat,
  'product' : Product,
});
export const Rank = IDL.Record({
  'id' : IDL.Nat,
  'tier' : IDL.Text,
  'product' : Product,
});
export const ProductType = IDL.Variant({
  'coinBundle' : CoinBundle,
  'rank' : Rank,
});
export const Purchase = IDL.Record({
  'id' : IDL.Nat,
  'paymentSessionId' : IDL.Text,
  'purchaseTime' : Time,
  'productId' : IDL.Nat,
  'productType' : ProductType,
  'caller' : IDL.Principal,
  'priceCents' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
});
export const StoreInfo = IDL.Record({
  'coinBundles' : IDL.Vec(CoinBundle),
  'coinBundleMultiplier' : IDL.Nat,
  'currency' : IDL.Text,
  'rankDescription' : IDL.Text,
  'ranks' : IDL.Vec(Rank),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

// Manual order types
export const ManualOrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceINR' : IDL.Nat,
});
export const ManualOrder = IDL.Record({
  'id' : IDL.Nat,
  'timestamp' : Time,
  'username' : IDL.Text,
  'email' : IDL.Text,
  'items' : IDL.Vec(ManualOrderItem),
  'totalINR' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'screenshotBase64' : IDL.Text,
  'verified' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoinBundle' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addRank' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getManualOrders' : IDL.Func([], [IDL.Vec(ManualOrder)], ['query']),
  'getPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getStore' : IDL.Func([], [StoreInfo], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markManualOrderVerified' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'purchaseProduct' : IDL.Func(
      [IDL.Nat, ProductType, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitManualOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ManualOrderItem), IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'priceCents' : IDL.Nat,
  });
  const CoinBundle = IDL.Record({
    'id' : IDL.Nat,
    'coins' : IDL.Nat,
    'product' : Product,
  });
  const Rank = IDL.Record({
    'id' : IDL.Nat,
    'tier' : IDL.Text,
    'product' : Product,
  });
  const ProductType = IDL.Variant({ 'coinBundle' : CoinBundle, 'rank' : Rank });
  const Purchase = IDL.Record({
    'id' : IDL.Nat,
    'paymentSessionId' : IDL.Text,
    'purchaseTime' : Time,
    'productId' : IDL.Nat,
    'productType' : ProductType,
    'caller' : IDL.Principal,
    'priceCents' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
  });
  const StoreInfo = IDL.Record({
    'coinBundles' : IDL.Vec(CoinBundle),
    'coinBundleMultiplier' : IDL.Nat,
    'currency' : IDL.Text,
    'rankDescription' : IDL.Text,
    'ranks' : IDL.Vec(Rank),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ManualOrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceINR' : IDL.Nat,
  });
  const ManualOrder = IDL.Record({
    'id' : IDL.Nat,
    'timestamp' : Time,
    'username' : IDL.Text,
    'email' : IDL.Text,
    'items' : IDL.Vec(ManualOrderItem),
    'totalINR' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'screenshotBase64' : IDL.Text,
    'verified' : IDL.Bool,
  });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoinBundle' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addRank' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getManualOrders' : IDL.Func([], [IDL.Vec(ManualOrder)], ['query']),
    'getPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getStore' : IDL.Func([], [StoreInfo], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markManualOrderVerified' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'purchaseProduct' : IDL.Func(
        [IDL.Nat, ProductType, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitManualOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ManualOrderItem), IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
